name: maven_build
author: ctw04398
description: maven_build
runs:
  using: composite
  steps:
    - run: |
        echo "Update me with the necessary commands"
      shell: bash
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

